import type { ToolDefinition } from "@altship/tool-design";
import type { AuthBinding } from "./auth.js";

export function packageJsonTemplate(pkgName: string): string {
  return JSON.stringify(
    {
      name: pkgName,
      version: "0.1.0",
      private: true,
      type: "module",
      scripts: {
        build: "tsc -p tsconfig.json",
        start: "node dist/server.js",
        dev: "tsx src/server.ts",
      },
      dependencies: {
        "@modelcontextprotocol/sdk": "^1.30.0",
        ajv: "^8.17.1",
        "ajv-formats": "^3.0.1",
      },
      devDependencies: {
        "@types/node": "^22.10.2",
        tsx: "^4.19.2",
        typescript: "^5.7.2",
      },
      engines: { node: ">=20" },
    },
    null,
    2,
  );
}

export function tsconfigTemplate(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: "ES2022",
        module: "NodeNext",
        moduleResolution: "NodeNext",
        lib: ["ES2022"],
        outDir: "dist",
        rootDir: "src",
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
      },
      include: ["src"],
    },
    null,
    2,
  );
}

export function configTemplate(baseUrlEnvVar: string, defaultBaseUrl: string): string {
  return `// Generated by altship-mcp. Do not hand-edit — regenerate from the source spec instead.

/** Base URL of the upstream API. Override with ${baseUrlEnvVar} for staging/local testing. */
export const BASE_URL = process.env.${baseUrlEnvVar} ?? ${JSON.stringify(defaultBaseUrl)};
`;
}

export function authTemplate(binding: AuthBinding): string {
  const header = `// Generated by altship-mcp. Do not hand-edit — regenerate from the source spec instead.
//
// Credentials are resolved from an environment variable at runtime and are
// never embedded in this file or logged. See ../.env.example.

export function assertAuthConfigured(): void {
`;

  const footer = `
/**
 * Applies auth to an outgoing request. \`callerToken\` is the bearer token the
 * MCP client sent with this specific call (from RequestHandlerExtra.authInfo)
 * -- only used in "passthrough" mode, where each end-user's own token is
 * forwarded to the upstream API instead of a single shared server-side
 * credential. We don't validate it ourselves; the upstream API does, exactly
 * as it would if the caller had hit it directly.
 */
export function applyAuth(url: URL, headers: Record<string, string>, callerToken?: string): void {
${applyBody(binding)}
}
`;

  if (binding.kind === "none" || binding.kind === "passthrough") {
    const comment =
      binding.kind === "passthrough"
        ? "  // Passthrough auth: nothing to configure server-side, the caller supplies their own token per request."
        : "  // No supported auth scheme was found in the source spec; requests are unauthenticated.";
    return `${header}${comment}\n}\n${footer}`;
  }

  return `${header}  if (!process.env.${binding.envVar}) {
    throw new Error(
      "Missing required environment variable ${binding.envVar}. Set it before starting this server."
    );
  }
}
${footer}`;
}

function applyBody(binding: AuthBinding): string {
  switch (binding.kind) {
    case "apiKey-header":
      return `  headers[${JSON.stringify(binding.paramName)}] = process.env.${binding.envVar}!;`;
    case "apiKey-query":
      return `  url.searchParams.set(${JSON.stringify(binding.paramName)}, process.env.${binding.envVar}!);`;
    case "bearer":
      return `  headers["authorization"] = \`Bearer \${process.env.${binding.envVar}}\`;`;
    case "basic": {
      return `  headers["authorization"] = \`Basic \${Buffer.from(process.env.${binding.envVar}!).toString("base64")}\`;`;
    }
    case "passthrough":
      return `  if (!callerToken) {
    throw new Error("This tool requires the caller's own bearer token, but none was provided with the request.");
  }
  headers["authorization"] = \`Bearer \${callerToken}\`;`;
    case "none":
    default:
      return "  // no-op";
  }
}

export function toolsDataTemplate(tools: ToolDefinition[]): string {
  const serializable = tools.map((t) => ({
    name: t.name,
    description: t.description || `${t.method} ${t.path}`,
    inputSchema: t.inputSchema,
    parameterMap: t.parameterMap,
    method: t.method,
    path: t.path,
    destructive: t.destructive,
  }));

  return `// Generated by altship-mcp. Do not hand-edit — regenerate from the source spec instead.
import type { GeneratedTool } from "./types.js";

export const TOOLS: GeneratedTool[] = ${JSON.stringify(serializable, null, 2)};
`;
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/**
 * A minimal, dependency-free landing page for the generated server's root
 * URL, so a human who follows the deployment link sees something useful
 * (what this MCP server does, which tools it exposes) instead of a 404 or
 * a bare JSON endpoint.
 */
export function docsPageTemplate(apiTitle: string, tools: ToolDefinition[], mcpPath: string): string {
  const toolRows = tools
    .map(
      (t) => `
      <div class="tool">
        <div class="tool-head">
          <code class="method">${escapeHtml(t.method)}</code>
          <code class="path">${escapeHtml(t.path)}</code>
          <span class="arrow">&rarr;</span>
          <strong>${escapeHtml(t.name)}</strong>
          ${t.destructive ? '<span class="flag">destructive</span>' : ""}
        </div>
        ${t.description ? `<p class="desc">${escapeHtml(t.description)}</p>` : ""}
        ${
          Object.keys(t.inputSchema.properties).length > 0
            ? `<p class="params">Parameters: ${Object.keys(t.inputSchema.properties)
                .map((p) => `<code>${escapeHtml(p)}</code>`)
                .join(", ")}</p>`
            : ""
        }
      </div>`,
    )
    .join("\n");

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${escapeHtml(apiTitle)} MCP Server</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; max-width: 720px; margin: 0 auto; padding: 2.5rem 1.5rem 4rem; color: #1a1d23; background: #f6f7f9; }
  h1 { font-size: 1.5rem; margin-bottom: 0.25rem; }
  .subtitle { color: #5b6270; margin-top: 0; }
  .endpoint { background: #fff; border: 1px solid #e3e5e9; border-radius: 8px; padding: 1rem 1.25rem; margin: 1.5rem 0; font-size: 0.9rem; }
  .endpoint code { background: #f0f1f3; padding: 0.1rem 0.4rem; border-radius: 4px; }
  .tool { background: #fff; border: 1px solid #e3e5e9; border-radius: 8px; padding: 1rem 1.25rem; margin-bottom: 0.75rem; }
  .tool-head { display: flex; align-items: center; gap: 0.5rem; flex-wrap: wrap; }
  .method { font-size: 0.75rem; font-weight: 600; background: #1a1d23; color: #fff; padding: 0.1rem 0.4rem; border-radius: 4px; }
  .path, .params code { font-size: 0.8rem; color: #5b6270; background: #f0f1f3; padding: 0.1rem 0.4rem; border-radius: 4px; }
  .arrow { color: #b0b4bc; }
  .flag { font-size: 0.7rem; padding: 0.1rem 0.4rem; border-radius: 4px; font-weight: 600; background: #fdecec; color: #a3231f; }
  .desc { margin: 0.4rem 0 0; font-size: 0.85rem; color: #3a3d44; }
  .params { margin: 0.4rem 0 0; font-size: 0.8rem; color: #5b6270; }
</style>
</head>
<body>
  <h1>${escapeHtml(apiTitle)} MCP Server</h1>
  <p class="subtitle">Generated by altship-mcp. Exposes ${tools.length} tool(s) over the Model Context Protocol.</p>

  <div class="endpoint">
    MCP endpoint (Streamable HTTP): <code>${escapeHtml(mcpPath)}</code><br/>
    Health check: <code>/api/health</code>
  </div>

  <h2>Tools</h2>
  ${toolRows || "<p>No tools configured.</p>"}
</body>
</html>
`;
}

/** Wraps a rendered docs page as a TS module so the Node target (which has no static-file serving) can import and serve it inline. */
export function docsModuleTemplate(html: string): string {
  return `// Generated by altship-mcp. Do not hand-edit — regenerate from the source spec instead.
export const DOCS_HTML = ${JSON.stringify(html)};
`;
}

export function typesTemplate(): string {
  return `// Generated by altship-mcp. Do not hand-edit — regenerate from the source spec instead.

export type ParameterSource = "path" | "query" | "body" | "body-raw";

export interface ParameterMapping {
  source: ParameterSource;
  originalName: string;
}

export interface JsonSchemaProperty {
  type?: string;
  description?: string;
  items?: JsonSchemaProperty;
  enum?: unknown[];
  format?: string;
  [key: string]: unknown;
}

export interface JsonSchema {
  type: "object";
  properties: Record<string, JsonSchemaProperty>;
  required?: string[];
}

export interface GeneratedTool {
  name: string;
  description: string;
  inputSchema: JsonSchema;
  parameterMap: Record<string, ParameterMapping>;
  method: string;
  path: string;
  destructive: boolean;
}
`;
}

export function clientTemplate(): string {
  return `// Generated by altship-mcp. Do not hand-edit — regenerate from the source spec instead.
import { BASE_URL } from "./config.js";
import { applyAuth } from "./auth.js";
import type { GeneratedTool } from "./types.js";

export interface ExecutionResult {
  status: number;
  ok: boolean;
  body: unknown;
}

/**
 * Builds and sends the HTTP request for a tool call from its declarative
 * parameter map, then normalizes the response. Credentials are applied
 * here and never appear in the returned result, logs, or thrown errors.
 */
export async function executeTool(
  tool: GeneratedTool,
  args: Record<string, unknown>,
  callerToken?: string,
): Promise<ExecutionResult> {
  let path = tool.path;
  const query = new URLSearchParams();
  const bodyFields: Record<string, unknown> = {};
  let rawBody: unknown;
  let hasBody = false;

  for (const [propName, mapping] of Object.entries(tool.parameterMap)) {
    const value = args[propName];
    if (value === undefined || value === null) continue;

    if (mapping.source === "path") {
      path = path.replace(\`{\${mapping.originalName}}\`, encodeURIComponent(String(value)));
    } else if (mapping.source === "query") {
      query.set(mapping.originalName, String(value));
    } else if (mapping.source === "body") {
      bodyFields[mapping.originalName] = value;
      hasBody = true;
    } else if (mapping.source === "body-raw") {
      rawBody = value;
      hasBody = true;
    }
  }

  const finalUrl = new URL(BASE_URL.replace(/\\/$/, "") + path);
  query.forEach((v, k) => finalUrl.searchParams.set(k, v));

  const headers: Record<string, string> = { accept: "application/json" };
  applyAuth(finalUrl, headers, callerToken);

  let body: string | undefined;
  if (hasBody) {
    body = JSON.stringify(rawBody !== undefined ? rawBody : bodyFields);
    headers["content-type"] = "application/json";
  }

  const response = await fetch(finalUrl, { method: tool.method, headers, body });
  const contentType = response.headers.get("content-type") ?? "";
  const responseBody = contentType.includes("json")
    ? await response.json().catch(() => null)
    : await response.text();

  return { status: response.status, ok: response.ok, body: responseBody };
}
`;
}

/**
 * Shared by every deployment target (Node stdio/HTTP, Vercel): builds a
 * fresh, unconnected Server per call. There's no per-client session state
 * worth keeping for a stateless API adapter like this one, so "create one
 * per request" is correct in every mode, not just serverless.
 */
export function mcpFactoryTemplate(serverName: string): string {
  return `// Generated by altship-mcp. Do not hand-edit — regenerate from the source spec instead.
import { Ajv } from "ajv";
import addFormatsPkg from "ajv-formats";
import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { CallToolRequestSchema, ListToolsRequestSchema } from "@modelcontextprotocol/sdk/types.js";
import { TOOLS } from "./tools.js";
import { executeTool } from "./client.js";

// ajv-formats ships CJS types with an ESM-shaped \`export default\`, which
// trips up TS's NodeNext interop (the import resolves to the module
// namespace, not the function) -- unwrap it explicitly rather than fighting
// the type checker on every regenerate.
const addFormats = ((addFormatsPkg as any).default ?? addFormatsPkg) as (ajv: Ajv) => void;

const ajv = new Ajv({ allErrors: true, strict: false });
addFormats(ajv);
const validators = new Map(TOOLS.map((tool) => [tool.name, ajv.compile(tool.inputSchema)]));

export function createMcpServer(): Server {
  const server = new Server(
    { name: ${JSON.stringify(serverName)}, version: "0.1.0" },
    { capabilities: { tools: {} } },
  );

  server.setRequestHandler(ListToolsRequestSchema, async () => ({
    tools: TOOLS.map((tool) => ({
      name: tool.name,
      description: tool.description,
      inputSchema: tool.inputSchema,
    })),
  }));

  server.setRequestHandler(CallToolRequestSchema, async (request, extra) => {
    const { name, arguments: args } = request.params;
    // Only populated over Streamable HTTP when the transport attached an
    // incoming Authorization header (see server.ts / api/mcp.ts) -- this is
    // the calling end-user's own token in "passthrough" auth mode.
    const callerToken = extra.authInfo?.token;
    const tool = TOOLS.find((t) => t.name === name);

    if (!tool) {
      return { content: [{ type: "text", text: \`Unknown tool: \${name}\` }], isError: true };
    }

    const validate = validators.get(name)!;
    if (!validate(args ?? {})) {
      const message = ajv.errorsText(validate.errors, { separator: "; " });
      return { content: [{ type: "text", text: \`Invalid input: \${message}\` }], isError: true };
    }

    try {
      const result = await executeTool(tool, (args ?? {}) as Record<string, unknown>, callerToken);
      const text =
        result.ok && (result.body === null || result.body === undefined)
          ? \`OK (\${result.status})\`
          : JSON.stringify(result.body, null, 2);
      return {
        content: [{ type: "text", text }],
        isError: !result.ok,
      };
    } catch (err) {
      // Never leak the raw error upstream in case it embeds request internals —
      // surface a stable message instead.
      return { content: [{ type: "text", text: \`Request failed: \${err instanceof Error ? err.message : "unknown error"}\` }], isError: true };
    }
  });

  return server;
}

/**
 * Builds the SDK's AuthInfo shape from a raw "Authorization: Bearer <token>"
 * header, so it can be attached to the incoming request as \`req.auth\` before
 * handing off to the transport -- the SDK then surfaces it to every tool
 * call as \`extra.authInfo\`. We don't verify the token (see auth.ts); this
 * just carries it through unchanged for "passthrough" mode to relay.
 */
export function parseBearerToken(authorizationHeader: string | string[] | undefined) {
  const header = Array.isArray(authorizationHeader) ? authorizationHeader[0] : authorizationHeader;
  const match = header?.match(/^Bearer\\s+(.+)$/i);
  if (!match) return undefined;
  return { token: match[1], clientId: "passthrough", scopes: [] };
}
`;
}

export function serverTemplate(): string {
  return `// Generated by altship-mcp. Do not hand-edit — regenerate from the source spec instead.
import http from "node:http";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import { createMcpServer, parseBearerToken } from "./mcp-factory.js";
import { assertAuthConfigured } from "./auth.js";
import { DOCS_HTML } from "./docs.js";

assertAuthConfigured();

const jsonRpcMethodNotAllowed = JSON.stringify({
  jsonrpc: "2.0",
  error: { code: -32000, message: "Method not allowed." },
  id: null,
});

/**
 * MCP over Streamable HTTP, stateless (no sessionIdGenerator): each POST
 * /mcp gets its own Server + transport pair, since there's no per-client
 * state worth keeping between calls for a stateless API adapter like this
 * one. Also exposes GET /health for container/orchestrator health checks.
 */
function startHttpServer(port: number): void {
  const httpServer = http.createServer(async (req, res) => {
    const url = new URL(req.url ?? "/", "http://localhost");

    if (req.method === "GET" && url.pathname === "/health") {
      res.writeHead(200, { "content-type": "application/json" }).end(JSON.stringify({ status: "ok" }));
      return;
    }

    if (req.method === "GET" && url.pathname === "/") {
      res.writeHead(200, { "content-type": "text/html; charset=utf-8" }).end(DOCS_HTML);
      return;
    }

    if (url.pathname !== "/mcp") {
      res.writeHead(404).end();
      return;
    }

    if (req.method !== "POST") {
      res.writeHead(405, { "content-type": "application/json" }).end(jsonRpcMethodNotAllowed);
      return;
    }

    const server = createMcpServer();
    try {
      const transport = new StreamableHTTPServerTransport({ sessionIdGenerator: undefined });
      res.on("close", () => {
        transport.close();
        server.close();
      });
      await server.connect(transport);
      (req as typeof req & { auth?: unknown }).auth = parseBearerToken(req.headers.authorization);
      await transport.handleRequest(req, res);
    } catch (err) {
      console.error("Error handling MCP request:", err);
      if (!res.headersSent) {
        res.writeHead(500, { "content-type": "application/json" }).end(
          JSON.stringify({
            jsonrpc: "2.0",
            error: { code: -32603, message: "Internal server error" },
            id: null,
          }),
        );
      }
    }
  });

  httpServer.listen(port, () => {
    console.log(\`MCP HTTP server listening on port \${port} (POST /mcp, GET /health)\`);
  });
}

if (process.env.MCP_TRANSPORT === "http") {
  startHttpServer(Number(process.env.PORT ?? 8080));
} else {
  const server = createMcpServer();
  const transport = new StdioServerTransport();
  await server.connect(transport);
}
`;
}

export function vercelMcpHandlerTemplate(): string {
  return `// Generated by altship-mcp. Do not hand-edit — regenerate from the source spec instead.
import type { VercelRequest, VercelResponse } from "@vercel/node";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import { createMcpServer, parseBearerToken } from "../lib/mcp-factory.js";
import { assertAuthConfigured } from "../lib/auth.js";

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== "POST") {
    res.status(405).json({ jsonrpc: "2.0", error: { code: -32000, message: "Method not allowed." }, id: null });
    return;
  }

  // Checked per-invocation rather than at module load: a serverless cold
  // start crashing on a missing env var produces an opaque platform error,
  // whereas catching it here returns a clean, diagnosable JSON-RPC error.
  try {
    assertAuthConfigured();
  } catch (err) {
    res.status(500).json({
      jsonrpc: "2.0",
      error: { code: -32603, message: err instanceof Error ? err.message : "Server misconfigured" },
      id: null,
    });
    return;
  }

  const server = createMcpServer();
  try {
    const transport = new StreamableHTTPServerTransport({ sessionIdGenerator: undefined });
    res.on("close", () => {
      transport.close();
      server.close();
    });
    await server.connect(transport);
    const nodeReq = req as unknown as import("node:http").IncomingMessage & { auth?: unknown };
    nodeReq.auth = parseBearerToken(req.headers.authorization);
    await transport.handleRequest(nodeReq, res as unknown as import("node:http").ServerResponse, req.body);
  } catch (err) {
    console.error("Error handling MCP request:", err);
    if (!res.headersSent) {
      res.status(500).json({ jsonrpc: "2.0", error: { code: -32603, message: "Internal server error" }, id: null });
    }
  }
}
`;
}

export function vercelHealthHandlerTemplate(): string {
  return `// Generated by altship-mcp. Do not hand-edit — regenerate from the source spec instead.
import type { VercelRequest, VercelResponse } from "@vercel/node";

export default function handler(_req: VercelRequest, res: VercelResponse) {
  res.status(200).json({ status: "ok" });
}
`;
}

export function vercelPackageJsonTemplate(pkgName: string): string {
  return JSON.stringify(
    {
      name: pkgName,
      version: "0.1.0",
      private: true,
      type: "module",
      dependencies: {
        "@modelcontextprotocol/sdk": "^1.30.0",
        ajv: "^8.17.1",
        "ajv-formats": "^3.0.1",
      },
      devDependencies: {
        "@types/node": "^22.10.2",
        "@vercel/node": "^3.2.24",
        typescript: "^5.7.2",
      },
    },
    null,
    2,
  );
}

export function vercelTsconfigTemplate(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: "ES2022",
        module: "ESNext",
        moduleResolution: "Bundler",
        lib: ["ES2022"],
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        noEmit: true,
      },
      include: ["api", "lib"],
    },
    null,
    2,
  );
}

export function vercelGitignoreTemplate(): string {
  return "node_modules/\n.vercel/\n.env\n.env.*\n!.env.example\n";
}

function needsEnvVar(binding: AuthBinding): boolean {
  return binding.kind !== "none" && binding.kind !== "passthrough";
}

function authDescription(binding: AuthBinding): string {
  if (binding.kind === "passthrough") {
    return "None to configure here — each caller forwards their own bearer token, which is relayed to the upstream API as-is.";
  }
  if (binding.kind === "none") {
    return "No credentials required (no supported auth scheme was found in the source spec).";
  }
  return `\`${binding.envVar}\` — required credential for the upstream API.`;
}

export function vercelReadmeTemplate(apiTitle: string, binding: AuthBinding, toolCount: number): string {
  return `# ${apiTitle} MCP Server (Vercel)

Generated by [altship-mcp](https://github.com) from the ${apiTitle} OpenAPI specification. Exposes ${toolCount} tool(s) over MCP via Streamable HTTP, as Vercel serverless functions.

## Deploy

\`\`\`
npx vercel login          # once, interactively
npx vercel link           # links this directory to a Vercel project
${needsEnvVar(binding) ? `npx vercel env add ${binding.envVar}\n` : ""}npx vercel deploy --prod
\`\`\`

Required environment variables: ${authDescription(binding)}

Your MCP endpoint will be \`https://<your-project>.vercel.app/api/mcp\` (health check at \`/api/health\`). Point any MCP-compatible client that supports Streamable HTTP at that URL.
`;
}

export function envExampleTemplate(binding: AuthBinding, baseUrlEnvVar: string): string {
  const lines = [
    `# ${baseUrlEnvVar}=https://api.example.com  # optional override of the spec's default server URL`,
    "# MCP_TRANSPORT=http  # default is stdio; set to \"http\" for a hosted deployment",
    "# PORT=8080           # only used when MCP_TRANSPORT=http",
  ];
  if (needsEnvVar(binding)) {
    lines.push(`${binding.envVar}=`);
  }
  return lines.join("\n") + "\n";
}

export function dockerfileTemplate(): string {
  return `FROM node:20-slim AS build
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install
COPY tsconfig.json ./
COPY src ./src
RUN npm run build

FROM node:20-slim
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app/package.json ./
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist
# Only takes effect when run with MCP_TRANSPORT=http (see README) --
# stdio mode, the default, doesn't listen on any port.
EXPOSE 8080
CMD ["node", "dist/server.js"]
`;
}

export function readmeTemplate(apiTitle: string, binding: AuthBinding, toolCount: number): string {
  return `# ${apiTitle} MCP Server

Generated by [altship-mcp](https://github.com) from the ${apiTitle} OpenAPI specification. Exposes ${toolCount} tool(s) over the Model Context Protocol.

## Configure

Copy \`.env.example\` to \`.env\` and fill in:

- ${authDescription(binding)}

## Run

\`\`\`
npm install
npm run build
npm start
\`\`\`

Or with Docker:

\`\`\`
docker build -t ${apiTitle.toLowerCase().replace(/\\s+/g, "-")}-mcp .
docker run --env-file .env ${apiTitle.toLowerCase().replace(/\\s+/g, "-")}-mcp
\`\`\`

## Transport

By default this server speaks MCP over **stdio** — point any MCP-compatible client (or [@altship/playground](https://github.com)) at the built binary (\`node dist/server.js\`) or the Docker image's stdin/stdout, e.g. \`docker run -i --env-file .env <image>\`.

For a hosted deployment, set \`MCP_TRANSPORT=http\` to instead serve MCP over **Streamable HTTP**:

\`\`\`
MCP_TRANSPORT=http PORT=8080 node dist/server.js
\`\`\`

or with Docker:

\`\`\`
docker run -p 8080:8080 --env-file .env -e MCP_TRANSPORT=http ${apiTitle.toLowerCase().replace(/\\s+/g, "-")}-mcp
\`\`\`

This exposes \`POST /mcp\` (the MCP endpoint — stateless, no session tracking) and \`GET /health\` (for container/load-balancer health checks).
`;
}
