import type { ToolDefinition } from "@altship/tool-design";
import type { AuthBinding } from "./auth.js";

export function packageJsonTemplate(pkgName: string): string {
  return JSON.stringify(
    {
      name: pkgName,
      version: "0.1.0",
      private: true,
      type: "module",
      scripts: {
        build: "tsc -p tsconfig.json",
        start: "node dist/server.js",
        dev: "tsx src/server.ts",
      },
      dependencies: {
        "@modelcontextprotocol/sdk": "^1.30.0",
        ajv: "^8.17.1",
      },
      devDependencies: {
        "@types/node": "^22.10.2",
        tsx: "^4.19.2",
        typescript: "^5.7.2",
      },
      engines: { node: ">=20" },
    },
    null,
    2,
  );
}

export function tsconfigTemplate(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: "ES2022",
        module: "NodeNext",
        moduleResolution: "NodeNext",
        lib: ["ES2022"],
        outDir: "dist",
        rootDir: "src",
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
      },
      include: ["src"],
    },
    null,
    2,
  );
}

export function configTemplate(baseUrlEnvVar: string, defaultBaseUrl: string): string {
  return `// Generated by altship-mcp. Do not hand-edit — regenerate from the source spec instead.

/** Base URL of the upstream API. Override with ${baseUrlEnvVar} for staging/local testing. */
export const BASE_URL = process.env.${baseUrlEnvVar} ?? ${JSON.stringify(defaultBaseUrl)};
`;
}

export function authTemplate(binding: AuthBinding): string {
  const header = `// Generated by altship-mcp. Do not hand-edit — regenerate from the source spec instead.
//
// Credentials are resolved from an environment variable at runtime and are
// never embedded in this file or logged. See ../.env.example.

export function assertAuthConfigured(): void {
`;

  const footer = `
export function applyAuth(url: URL, headers: Record<string, string>): void {
${applyBody(binding)}
}
`;

  if (binding.kind === "none") {
    return `${header}  // No supported auth scheme was found in the source spec; requests are unauthenticated.\n}\n${footer}`;
  }

  return `${header}  if (!process.env.${binding.envVar}) {
    throw new Error(
      "Missing required environment variable ${binding.envVar}. Set it before starting this server."
    );
  }
}
${footer}`;
}

function applyBody(binding: AuthBinding): string {
  switch (binding.kind) {
    case "apiKey-header":
      return `  headers[${JSON.stringify(binding.paramName)}] = process.env.${binding.envVar}!;`;
    case "apiKey-query":
      return `  url.searchParams.set(${JSON.stringify(binding.paramName)}, process.env.${binding.envVar}!);`;
    case "bearer":
      return `  headers["authorization"] = \`Bearer \${process.env.${binding.envVar}}\`;`;
    case "basic": {
      return `  headers["authorization"] = \`Basic \${Buffer.from(process.env.${binding.envVar}!).toString("base64")}\`;`;
    }
    case "none":
    default:
      return "  // no-op";
  }
}

export function toolsDataTemplate(tools: ToolDefinition[]): string {
  const serializable = tools.map((t) => ({
    name: t.name,
    description: t.description || `${t.method} ${t.path}`,
    inputSchema: t.inputSchema,
    parameterMap: t.parameterMap,
    method: t.method,
    path: t.path,
    destructive: t.destructive,
  }));

  return `// Generated by altship-mcp. Do not hand-edit — regenerate from the source spec instead.
import type { GeneratedTool } from "./types.js";

export const TOOLS: GeneratedTool[] = ${JSON.stringify(serializable, null, 2)};
`;
}

export function typesTemplate(): string {
  return `// Generated by altship-mcp. Do not hand-edit — regenerate from the source spec instead.

export type ParameterSource = "path" | "query" | "body" | "body-raw";

export interface ParameterMapping {
  source: ParameterSource;
  originalName: string;
}

export interface JsonSchemaProperty {
  type?: string;
  description?: string;
  items?: JsonSchemaProperty;
  enum?: unknown[];
  format?: string;
  [key: string]: unknown;
}

export interface JsonSchema {
  type: "object";
  properties: Record<string, JsonSchemaProperty>;
  required?: string[];
}

export interface GeneratedTool {
  name: string;
  description: string;
  inputSchema: JsonSchema;
  parameterMap: Record<string, ParameterMapping>;
  method: string;
  path: string;
  destructive: boolean;
}
`;
}

export function clientTemplate(): string {
  return `// Generated by altship-mcp. Do not hand-edit — regenerate from the source spec instead.
import { BASE_URL } from "./config.js";
import { applyAuth } from "./auth.js";
import type { GeneratedTool } from "./types.js";

export interface ExecutionResult {
  status: number;
  ok: boolean;
  body: unknown;
}

/**
 * Builds and sends the HTTP request for a tool call from its declarative
 * parameter map, then normalizes the response. Credentials are applied
 * here and never appear in the returned result, logs, or thrown errors.
 */
export async function executeTool(tool: GeneratedTool, args: Record<string, unknown>): Promise<ExecutionResult> {
  let path = tool.path;
  const query = new URLSearchParams();
  const bodyFields: Record<string, unknown> = {};
  let rawBody: unknown;
  let hasBody = false;

  for (const [propName, mapping] of Object.entries(tool.parameterMap)) {
    const value = args[propName];
    if (value === undefined || value === null) continue;

    if (mapping.source === "path") {
      path = path.replace(\`{\${mapping.originalName}}\`, encodeURIComponent(String(value)));
    } else if (mapping.source === "query") {
      query.set(mapping.originalName, String(value));
    } else if (mapping.source === "body") {
      bodyFields[mapping.originalName] = value;
      hasBody = true;
    } else if (mapping.source === "body-raw") {
      rawBody = value;
      hasBody = true;
    }
  }

  const finalUrl = new URL(BASE_URL.replace(/\\/$/, "") + path);
  query.forEach((v, k) => finalUrl.searchParams.set(k, v));

  const headers: Record<string, string> = { accept: "application/json" };
  applyAuth(finalUrl, headers);

  let body: string | undefined;
  if (hasBody) {
    body = JSON.stringify(rawBody !== undefined ? rawBody : bodyFields);
    headers["content-type"] = "application/json";
  }

  const response = await fetch(finalUrl, { method: tool.method, headers, body });
  const contentType = response.headers.get("content-type") ?? "";
  const responseBody = contentType.includes("json")
    ? await response.json().catch(() => null)
    : await response.text();

  return { status: response.status, ok: response.ok, body: responseBody };
}
`;
}

export function serverTemplate(serverName: string): string {
  return `// Generated by altship-mcp. Do not hand-edit — regenerate from the source spec instead.
import { Ajv } from "ajv";
import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { CallToolRequestSchema, ListToolsRequestSchema } from "@modelcontextprotocol/sdk/types.js";
import { TOOLS } from "./tools.js";
import { executeTool } from "./client.js";
import { assertAuthConfigured } from "./auth.js";

assertAuthConfigured();

const ajv = new Ajv({ allErrors: true, strict: false });
const validators = new Map(TOOLS.map((tool) => [tool.name, ajv.compile(tool.inputSchema)]));

const server = new Server(
  { name: ${JSON.stringify(serverName)}, version: "0.1.0" },
  { capabilities: { tools: {} } },
);

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: TOOLS.map((tool) => ({
    name: tool.name,
    description: tool.description,
    inputSchema: tool.inputSchema,
  })),
}));

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;
  const tool = TOOLS.find((t) => t.name === name);

  if (!tool) {
    return { content: [{ type: "text", text: \`Unknown tool: \${name}\` }], isError: true };
  }

  const validate = validators.get(name)!;
  if (!validate(args ?? {})) {
    const message = ajv.errorsText(validate.errors, { separator: "; " });
    return { content: [{ type: "text", text: \`Invalid input: \${message}\` }], isError: true };
  }

  try {
    const result = await executeTool(tool, (args ?? {}) as Record<string, unknown>);
    const text =
      result.ok && (result.body === null || result.body === undefined)
        ? \`OK (\${result.status})\`
        : JSON.stringify(result.body, null, 2);
    return {
      content: [{ type: "text", text }],
      isError: !result.ok,
    };
  } catch (err) {
    // Never leak the raw error upstream in case it embeds request internals —
    // surface a stable message instead.
    return { content: [{ type: "text", text: \`Request failed: \${err instanceof Error ? err.message : "unknown error"}\` }], isError: true };
  }
});

const transport = new StdioServerTransport();
await server.connect(transport);
`;
}

export function envExampleTemplate(binding: AuthBinding, baseUrlEnvVar: string): string {
  const lines = [`# ${baseUrlEnvVar}=https://api.example.com  # optional override of the spec's default server URL`];
  if (binding.kind !== "none") {
    lines.push(`${binding.envVar}=`);
  }
  return lines.join("\n") + "\n";
}

export function dockerfileTemplate(): string {
  return `FROM node:20-slim AS build
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install
COPY tsconfig.json ./
COPY src ./src
RUN npm run build

FROM node:20-slim
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app/package.json ./
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist
CMD ["node", "dist/server.js"]
`;
}

export function readmeTemplate(apiTitle: string, binding: AuthBinding, toolCount: number): string {
  return `# ${apiTitle} MCP Server

Generated by [altship-mcp](https://github.com) from the ${apiTitle} OpenAPI specification. Exposes ${toolCount} tool(s) over the Model Context Protocol.

## Configure

Copy \`.env.example\` to \`.env\` and fill in:

${binding.kind === "none" ? "- No credentials required (no supported auth scheme was found in the source spec)." : `- \`${binding.envVar}\` — required credential for the upstream API.`}

## Run

\`\`\`
npm install
npm run build
npm start
\`\`\`

Or with Docker:

\`\`\`
docker build -t ${apiTitle.toLowerCase().replace(/\\s+/g, "-")}-mcp .
docker run --env-file .env ${apiTitle.toLowerCase().replace(/\\s+/g, "-")}-mcp
\`\`\`

This server speaks MCP over stdio. Point any MCP-compatible client at the built binary (\`node dist/server.js\`) or the Docker image's stdin/stdout.
`;
}
